/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  OpenzeppelinContracts_contracts_access_Ownable_sol_Ownable,
  OpenzeppelinContracts_contracts_access_Ownable_sol_OwnableInterface,
} from "../OpenzeppelinContracts_contracts_access_Ownable_sol_Ownable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class OpenzeppelinContracts_contracts_access_Ownable_sol_Ownable__factory {
  static readonly abi = _abi;
  static createInterface(): OpenzeppelinContracts_contracts_access_Ownable_sol_OwnableInterface {
    return new utils.Interface(
      _abi
    ) as OpenzeppelinContracts_contracts_access_Ownable_sol_OwnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OpenzeppelinContracts_contracts_access_Ownable_sol_Ownable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OpenzeppelinContracts_contracts_access_Ownable_sol_Ownable;
  }
}
